---
- name: "Dotfiles add configuration files"
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ dotfiles_user }}"
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_user }}"
    mode: 0644
  with_items: ['aqua.yml']
  tags: dotfiles
