---
- name: "Deploy aqua configuration"
  become: true
  ansible.builtin.copy:
    src: "aqua.yml"
    dest: "/home/{{ dotfiles_user }}"
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_user }}"
    mode: 0644
  notify: update aqua

- name: Flush handlers
  ansible.builtin.meta: "flush_handlers"
