---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v4.49.0  # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.34.0
  - name: derailed/k9s@v0.27.4
  - name: derailed/popeye@v0.11.1
  - name: FairwindsOps/pluto@v5.18.4
  - name: go-task/task@v3.30.1
  - name: jesseduffield/lazygit@v0.40.2
  - name: junegunn/fzf@0.42.0
  - name: kubernetes-sigs/kind@v0.20.0
  - name: marp-team/marp-cli@v3.2.1
  - name: profclems/glab@v1.22.0
  - name: txn2/kubefwd@1.22.5
  - name: wagoodman/dive@v0.11.0
