---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v4.213.1  # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.54.0
  - name: derailed/k9s@v0.32.5
  - name: derailed/popeye@v0.21.3
  - name: FairwindsOps/pluto@v5.20
  - name: go-task/task@v3.38.0
  - name: jesseduffield/lazygit@v0.43.1
  - name: junegunn/fzf@v0.54.3
  - name: kubernetes-sigs/kind@v0.24.0
  - name: marp-team/marp-cli@v3.4.0
  - name: profclems/glab@v1.22.0
  - name: txn2/kubefwd@1.22.5
  - name: wagoodman/dive@v0.12.0
