---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v3.90.0  # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.32.1
  - name: junegunn/fzf@0.28.0
