---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v4.191.0  # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.49.2
  - name: derailed/k9s@v0.32.4
  - name: derailed/popeye@v0.21.3
  - name: FairwindsOps/pluto@v5.19.4
  - name: go-task/task@v3.37.2
  - name: jesseduffield/lazygit@v0.42.0
  - name: junegunn/fzf@0.52.1
  - name: kubernetes-sigs/kind@v0.23.0
  - name: marp-team/marp-cli@v3.4.0
  - name: profclems/glab@v1.22.0
  - name: txn2/kubefwd@1.22.5
  - name: wagoodman/dive@v0.12.0
