---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Install python3 for Ansible
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
      become: true
      changed_when: false
    - name: Install base packages
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: true
      with_items:
        - wget
        - curl
        - python3-pip
        - tar
        - unzip
      when: ansible_os_family == 'Debian'
    - name: Ensure user exists
      become: true
      ansible.builtin.user:
        name: "{{ lookup('ansible.builtin.env', 'USER') }}"
        create_home: true
        state: present

- name: Install aqua
  hosts: all
  gather_facts: true
  roles:
    - aqua_installer
