---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 2"

defaults:
  run:
    working-directory: 'ansible-roles'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'ansible-roles'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian10

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'ansible-roles'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install test dependencies.
        run: pip3 install ansible molecule==5.1.*  molecule-plugins[docker] docker ansible-lint

      - name: Run Molecule tests.
        run: molecule converge
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
